# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "666ecbdefc5fe4e7d17c629d4b5b7c14"
name = "bulk-data-upload"
handle = "bulk-data-upload"
application_url = "https://seconds-tsunami-stephanie-fg.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_products"

[auth]
redirect_urls = [
  "https://seconds-tsunami-stephanie-fg.trycloudflare.com/auth/callback",
  "https://seconds-tsunami-stephanie-fg.trycloudflare.com/auth/shopify/callback",
  "https://seconds-tsunami-stephanie-fg.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
