# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8895518da41bc492b0688f740c7c4e1b"
name = "lucrative-vertical-app"
handle = "lucrative-vertical-app-19"
application_url = "https://diet-occupational-phenomenon-pdt.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://diet-occupational-phenomenon-pdt.trycloudflare.com/auth/callback",
  "https://diet-occupational-phenomenon-pdt.trycloudflare.com/auth/shopify/callback",
  "https://diet-occupational-phenomenon-pdt.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
